browser:
  chrome_driver_path: /nix/store/3qnxr5x6gw3k9a9i7d0akz0m6bksbwff-chromedriver-125.0.6422.141/bin/chromedriver
forms:
  doubts:
  - form_url: https://docs.google.com/forms/d/e/1FAIpQLSfp4Cv5hh18zygNUVyL4HG3s3YjNeyodJVIfuW7fjOdq4LgIg/viewform
    name: Python Doubts
    sheet_url: https://docs.google.com/spreadsheets/d/1W0hFmsUwPYzNfS0Z4Q5eWW3hJF4_ADHff8Sr3DLRr2g/edit?gid=1633822374#gid=1633822374
  - form_url: https://docs.google.com/forms/d/1QDZtYLetdxsg5Z3N2utHrfJ3s0kbXoNCMrufUp_5EvM/edit
    name: Portfolio Doubts
    sheet_url: https://docs.google.com/spreadsheets/d/18BGkiwu6KIG-PdzHv7cmLrTO3vkdskUdViVY1QCp-QQ/edit?gid=1789136664#gid=1789136664
  - form_url: https://docs.google.com/forms/d/1NTqvVwAxjkkUqDBM6ip_LhTZ5wWRxU6rqvcqzJNZH8c/edit
    name: Machine Learning Doubts
    sheet_url: https://docs.google.com/spreadsheets/d/1pgvGx45SpISv37sU2C37VjcuAjBGAngxA0wpXuPILeU/edit?gid=394514113#gid=394514113
  - form_url: https://docs.google.com/forms/d/1bqhKuXsgYdh9LubGEfZjvRP2fmTH4IG8mtOZVvf_PIY/edit
    name: Deeplearning Doubts
    sheet_url: https://docs.google.com/spreadsheets/d/1pJawHJRnGVU_UHdp9iIGW4Ao8IcEAvh8BnLz4O0kCBw/edit?gid=1447172546#gid=1447172546
  - form_url: https://docs.google.com/forms/d/1iW95sQclwHQfMMEUZDYNRL3J_Ms1NA6W2uFbyA4Wha0/edit
    name: Statistics Doubts
    sheet_url: https://docs.google.com/spreadsheets/d/1ErgcmFCMS6ORbQzSVzY2KS6BRiZ8N6vr5rtjAkEa_vc/edit?gid=291863812#gid=291863812
  - form_url: https://docs.google.com/forms/d/1hy-VRpTz36koQ-KQD2wV_SqaKJsYCzooQvv7yVLBxSQ/edit
    name: SQL Doubts
    sheet_url: https://docs.google.com/spreadsheets/d/12QHBjvxlYS_juRQyDcRlO48W1yf2evl8I_uHB0Vp3Ao/edit?gid=69911782#gid=69911782
  - form_url: https://docs.google.com/forms/d/1e9_HOwM0_OhoTVBghxD2pnziDqccKbVelWojogjI928/edit
    name: Gen AI Doubts
    sheet_url: https://docs.google.com/spreadsheets/d/1pY3ig-F5Ic3Vb8eMQh8FBMdyIA-jE3uWGzmsgQU4ijQ/edit?gid=1254327300#gid=1254327300
  feedback:
    form_url: https://docs.google.com/forms/d/1GXVel21Qkmvp0sR4AFHPHX4RIBeijG_-7YdbVu6x2Cs/edit
    name: Feedback
    sheet_url: https://docs.google.com/spreadsheets/d/1FY9fTkFgPimYdnbTzHt6UpDDw19ZIq4B6xvnyDQl7IA/edit?gid=1752180823#gid=1752180823
